"""empty message

Revision ID: 48894500b8ea
Revises: ad169f15e3bf
Create Date: 2025-06-19 12:12:14.309507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48894500b8ea'
down_revision = 'ad169f15e3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
            batch_op.alter_column('senha',
                existing_type=sa.TEXT(),
                type_=sa.String(length=255),  # ou 255, se quiser mais espaço
                existing_nullable=False)


    with op.batch_alter_table('conversa', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
