"""empty message

Revision ID: ad169f15e3bf
Revises: 
Create Date: 2025-05-25 13:10:36.623372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad169f15e3bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=200), nullable=True),
    sa.Column('emocao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emocao_id'], ['emocoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('distorcoes_cognitivas')
    op.drop_table('emocoes_detectadas')
    op.drop_table('questionamentos_socraticos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('questionamentos_socraticos',
    sa.Column('questionamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_questionamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('questionamento_id', name='questionamentos_socraticos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('emocoes_detectadas',
    sa.Column('emocao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_emocao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo_emocao', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('emocao_id', name='emocoes_detectadas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('distorcoes_cognitivas',
    sa.Column('distorcao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emocao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questionamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emocao_id'], ['emocoes_detectadas.emocao_id'], name='distorcoes_cognitivas_emocao_id_fkey'),
    sa.ForeignKeyConstraint(['questionamento_id'], ['questionamentos_socraticos.questionamento_id'], name='distorcoes_cognitivas_questionamento_id_fkey'),
    sa.PrimaryKeyConstraint('distorcao_id', name='distorcoes_cognitivas_pkey')
    )
    op.drop_table('texto')
    op.drop_table('emocoes')
    # ### end Alembic commands ###
